project:
  type: website

website:
  title: "Statistical Yearbook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: chapters/index.qmd
        text: Chapters
  
  sidebar:
    contents:
      - href: chapters/box-office/index.qmd
        text: The Box Office
      
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



