project:
  type: website

website:
  title: "Statistical Yearbook"
  page-navigation: true
  bread-crumbs: true
  navbar:
    left:
      - href: index.qmd
        text: Dashboard
      - about.qmd
      - href: chapters/index.qmd
        text: Chapters
      - href: data-explorer.qmd
        text: Data explorer
  
  sidebar:
    style: docked
    collapse-level: 1
    contents:
      - section: "Statistical Yearbook 2022"
        href: chapters/index.qmd
        contents: 
          - section: The Box Office
            href: chapters/box-office/index.qmd
            contents:
              - href: chapters/box-office/admissions.qmd
                text: Admissions
              - href: chapters/box-office/history.qmd
                text: Annual UK admissions, 1935-2021
          - section: Top films
            href: chapters/top-films/index.qmd
            contents:
              - href: chapters/top-films/top-20.qmd
                text: The top 20 films
              - href: chapters/top-films/classification.qmd
                text: Releases and box office by BBFC classification
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid: 
      body-width: 800px

execute:
  freeze: auto



